<?php
/** 
 * @BTN1 New<br/>Section
 * @BTN2 Copy<br/>Section
 * @BTN3 ReDraw<br/>Section
 * @BTN4 ?
 * @BTN5 New
 * @BTN6 Load Blueprint
 * @BTN7 Save
 * @BTN8 Load Box
 * @DELETEBTN Remove<br/>Section
 * @blah
 */
class xBloxLang {
	// Used for Complex values.
	var $_LANG = array(
		'TUTOR' => array(
			'PAGE' => [
				array(
					'STEP' => []
				),
				array(
					'STEP' => []
				),
				array(
					'STEP' => []
				)
			]
		)

	);
}
?>