<?php
/** 
 * @BTN1 New<br/>Section
 * @BTN2 Copy<br/>Section
 * @BTN3 ReDraw<br/>Section
 * @BTN4 ?
 * @BTN5 New
 * @BTN6 Load Blueprint
 * @BTN7 Save
 * @BTN8 Load Box
 * @DELETEBTN Remove<br/>Section
 * @blah
 */
class xBloxLang {
	// Used for Complex values.
	var $_LANG = array(
		'BLOX' => array(
			'cover' => array(
				'name' => 'Coversheet',
				'desc' => 'Every great Website deserves a professionally sexy coverpage',
				'icon' => ''
			),
		),
		'JUMBO' => array(
			'HEAD' => 'Play in the Toy Blox',
			'QUOTE' => 'Welcome to your Online Bazaar! Here is where you connect to the world to exchange your goods and services.',
			'BTN'	=> array( 
				'jumpin'	=> array(
					'a' => 'Jump In <i class="fa fa-play"></i>  ',
					'class' => 'alert-info'
				)
			)
		),

	);
}
?>